name: CD
on:
  push:
    branches: [master]
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Connects to webgo server via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: s172.goserver.host
          port: 22
          username: web226
          password: ${{ secrets.WEBGO_PW }}
          script: |
            cd ~/www/js-dev.cloud/Modul-JavaScript/3-Praxisprojekte-Abschluss/js-3-professionalWebsite
            git checkout master
            git pull origin master
            git status
